[versions]
agp = "8.5.0"
kotlin = "1.9.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.10.0"
easypermissions = "3.0.0"
xpopup = "2.7.5"
agora-authentication = "2.1.3"
agora-rtc = "4.5.1.165"
#agora-rtc = "4.4.1.9"
agora-rtm = "2.2.4.2"
commons-codec = "1.19.0"
maas = "1.0.0"
gson = "2.13.1"
mmkv = "2.2.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
easypermissions = { group = "pub.devrel", name = "easypermissions", version.ref = "easypermissions" }
xpopup = { group = "com.github.li-xiaojun", name = "XPopup", version.ref = "xpopup" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
agora-authentication = { group = "io.agora", name = "authentication", version.ref = "agora-authentication" }
agora-rtc = { group = "io.agora.rtc", name = "agora-special-full", version.ref = "agora-rtc" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
agora-rtm = { group = "io.agora", name = "agora-rtm-special-lite", version.ref = "agora-rtm" }
mmkv = { group = "com.tencent", name = "mmkv-static", version.ref = "mmkv" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

